### ISSUE TITLE
Try FPS variation

### ISSUE THREAD

**Issue by DavidPgl** [lizrad/fpspf#22]
- No need for fog of war
- Maybe less chaotic

**Comment by kb173** [comment]
test comment

**Comment by kb173** [comment]
Added to a separate branch in https://github.com/lizrad/fpspf/commit/2ed06f00e61ca7422bba3b23dde83b652892c2ab. Vertical aiming isn't applied to the ghost, but with the current state of the game and the level, that should be no problem. Also, the player's own bullets aren't visible, I assume that's because the line rendering mesh is at exactly 90° to the camera. (but with the crosshairs, it's pretty obvious where you're shooting anyways)

We can play around with that, and if it turns out to be something we might want to look into further, I can try cleaning it up and merging as a config option.

**Comment by kb173** [comment]
We tested it, we'll see later what we do with it
